### PR TITLE
Customize

### PR DESCRIPTION
**Pull request by gabmarfer**
In my current project I have needed to add a couple of properties to UIEmptyStateDataSource (maybe they are useful for other users too):
- emptyStateImageViewTintColor: that allows to apply a tintColor to the imageView of UIEmptyStateView.
- emptyStateCenterYOffset: that allows to offset vertically the UIEmptyStateView.

Furthermore, I have modified the Podfile of the Example in order to use the local development pod. This makes easy to modify the library and test changes.

Thanks for sharing your work!

### CODE REVIEW

**Review by luispadron — CHANGES_REQUESTED** [review]
This is great, thanks for the awesome work!
If you don't mind, I think we should change `emptyStateCenterYOffset` to `emptyStateViewCenterYOffset`, while this is a longer name, it matches the rest of the API and is more explicit. 

Also, the doc comment  for `UIEmptyStateView.centerYConstraint` has a misc. comma. 

Finally, we should run Jazzy to update the docs/ folder. 
You can do so by `./run-jazzy.sh`. Thanks!

**Comment by gabmarfer** [comment]
Changes done. Thanks again!

**Review by luispadron — APPROVED** [review]

**Comment by luispadron** [comment]
I'll update changelog and get this pushed out to version 3.1.0 soon!

**Comment by luispadron** [comment]
Now in [version 3.1.0](https://github.com/luispadron/UIEmptyState/releases/tag/v3.1.0) thanks again!

**Pull request merged**
